project:
  type: book
  output-dir: docs

book:
  title: "Macroeconomy"
  author: "Norah Jones"
  date: "3/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - Pulse
      - brand
  pdf:
    documentclass: scrreprt



